#!/bin/bash

# Завантаження останньої версії WordPress
curl -O https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz

# Копіювання файлив в директорію веб-сервера
sudo rsync -av wordpress/ /var/www/html/

# Створення бази даних та користувача MySQL
mysql -uroot -p -e "CREATE DATABASE wordpress; \
CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'password'; \
GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost'; \
FLUSH PRIVILEGES;"

# Конфігурація WordPress
cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
sed -i "s/database_name_here/wordpress/g" /var/www/html/wp-config.php
sed -i "s/username_here/wpuser/g" /var/www/html/wp-config.php
sed -i "s/password_here/password/g" /var/www/html/wp-config.php

# Додавання секретного ключа
curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> /var/www/html/wp-config.php

# Налаштування прав доступу до файлів
sudo chown -R www-data:www-data /var/www/html/
sudo chmod -R 755 /var/www/html/

# Вивід інформації про успішне завершення розгортання
echo "WordPress has been deployed successfully."
